apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: crd-extractor
spec:
  version: {{ .TagName }}
  homepage: https://github.com/datreeio/CRDs-catalog
  shortDescription: Extract CRDs from your cluster and convert them to JSON schema
  description: |
    This plugin extracts CRDs from your cluster and converts them to JSON schema.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    {{addURIAndSha "https://github.com/datreeio/CRDs-catalog/releases/download/{{ .TagName }}/kubectl-crd-extractor.zip" .TagName }}
    files:
    - from: "kubectl-crd-extractor"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-crd-extractor
    